view commit
yosukehirai90/chat-space pull request #2
Opened 2019-02-02 13:23 UTC by yosukehirai90

https://gyazo.com/c9ad5665de26168ee465e777d01e6ffb

2019-02-02 13:32 UTC, TOMARUMARU reviewed
まずコミットをきちんと分けましょう。その際コミット名もきちんと何をしたか命名しましょう。

PR名もしっかり命名しましょう。何をこのブランチで実装したのか見る人がわかるようにです。

また、WHATとWHYもきちんと書きましょう！

ファイルの最後は改行を入れましょう。数ファイルで入ってないです！

2019-02-02 13:32 UTC, TOMARUMARU commented on app/assets/stylesheets/application.css.scss
> +html, body, .wrapper, .side-bar, .main {
application.scssはimportするだけにして、他の記述は別ファイルに切り分けましょう。

2019-02-02 13:32 UTC, TOMARUMARU commented on app/views/layouts/mailer.text.haml
> += yield
mailerファイルなど使用しないものは削除しましょう。

2019-02-03 08:02 UTC, ghost requested changes

2019-02-03 08:02 UTC, hiroki5123 commented on app/assets/stylesheets/application.css.scss
> +html, body, .wrapper, .side-bar, .main {
こちらまだ修正されてません。

2019-02-03 08:02 UTC, hiroki5123 commented on app/views/messages/_message.html.haml
> +
最後に空行いれてください。

2019-02-03 08:02 UTC, hiroki5123 commented on app/views/messages/_sidebar.html.haml
> +
最後に空行いれてください。

2019-02-03 08:02 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +  %body
ここより上はapplication.html.hamlに記載されていると思いますが、重複して書いているのはなぜですか？

2019-02-03 08:02 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +
最後に空行いれてください。

2019-02-03 08:02 UTC, hiroki5123 commented
WHATとWHYもきちんと書きましょう！
最初なんの実装をしたのかわかりませんでした。
指摘されたコメントに対しては必ず返信をしてください。

2019-02-03 08:29 UTC, yuki-uchida approved these changes
LGTMですが、頂いたコメントには必ずリプライする形で行った対応を記述してください

2019-02-03 08:37 UTC, merged